name: Metrics

on:
  push:
    braches: [ master ]
  pull_request:
    braches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout master brach from GitHub
        uses: actions/checkout@v2
        with:
          path: IntroUnitTesting

      - name: Step 2 - Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Step 3 - Checkout master branch of CK repository from GitHub
        uses: actions/checkout@v2
        with:
          repository: mauricioaniche/ck
          path: CK

      - name: Step 4 - Execute over JAR files
        run: cd CK ; mvn clean compile assembly:single ; cd target ; java -jar ck-0.6.5-SNAPSHOT-jar-with-dependencies.jar ../../IntroUnitTesting/

      - name: Step 5 - Upload metrics report
        uses: actions/upload-artifact@v2
        with:
          name: class.csv
          path: CK/target/class.csv