name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main brach from GitHub
        uses: actions/checkout@v2

      # Set up the JDK
      - name: Step 2 - Set up JDK 15.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.2

      # Runs maven to download the dependencies and test the files
      - name: Step 3.1 - Have GitHub Actions Build Maven calculatorExample Project
        run: cd code/calculatorExample ; mvn -B package --file pom.xml
        
      - name: Step 3.2 - Have GitHub Actions Build Maven complexNumber Project
        run: cd code/complexNumber ; mvn -B package --file pom.xml
        
      - name: Step 3.3 - Have GitHub Actions Build Maven EasyMockExample Project
        run: cd code/EasyMockExample ; mvn -B package --file pom.xml
        
      - name: Step 3.4 - Have GitHub Actions Build Maven MavenExamples Project
        run: cd code/MavenExamples/AppEx0 ; mvn -B package --file pom.xml
        
      - name: Step 3.5 - Have GitHub Actions Build Maven MockitoATM Project
        run: cd code/MockitoATM ; mvn -B package --file pom.xml
        
      - name: Step 3.6 - Have GitHub Actions Build Maven SeleniumTestExample Project (
        run: cd code/SeleniumTestExample
        
      - name: Step 3.7 - Have GitHub Actions Build Maven TDDExampleFactorial Project
        run: cd code/TDDExampleFactorial ; mvn -B package --file pom.xml
        
      - name: Step 3.8 - Have GitHub Actions Build Maven CucumberTestExample Project
        run: cd code/CucumberTestExample ; mvn -B package --file pom.xml
